### ISSUE TITLE
Publish binaries for cargo binstall

### ISSUE THREAD

**Issue by PolpOnline** [hakoerber/git-repo-manager#75]
It would be cool to support cargo binstall

[The docs are here](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md)

**Comment by hakoerber** [comment]
This requires automatically built binaries. See also #59.

As I am using either `cargo install` or the `PKGBUILD`, I did not get around to building this. If you want, you can give it a shot. A quick google search turns up some ready-to-use Github workflow configs.

**Comment by hakoerber** [comment]
And also #55

**Comment by hakoerber** [comment]
Done.

I used [`cargo-dist`](https://opensource.axo.dev/cargo-dist/) to create prebuilt, statically linked binaries. See https://github.com/hakoerber/git-repo-manager/releases/tag/v0.7.21

They can either be downloaded manually, or via `cargo-binstall`:

```
cargo binstall git-repo-manager
```
